default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: paintballdb
  password:

development:
  <<: *default
  database: upstack_dev

default: &default

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3